### PR TITLE
Update handling of cache_control changed in nginx 1.23.0 (Fixes #96)

### LINKED ISSUE #96: Nginx 1.23.0 header changes
Looks like nginx 1.23.0 header changes https://nginx.org/en/CHANGES makes this srcache-nginx-module module incompatible now

```
        ../srcache-nginx-module-0.32/src/ngx_http_srcache_util.c
ccache gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I/usr/local/zlib-cf/include -I/usr/local/nginx-dep/include -m64 -march=x86-64 -mavx -mavx2 -mpclmul -msse4 -msse4.1 -msse4.2 -DTCP_FASTOPEN=23 -falign-functions=32 -g -O3 -Wno-strict-aliasing -fstack-protector-strong -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wno-pointer-sign  -Wimplicit-fallthrough=0 -Wno-missing-profile -Wno-implicit-function-declaration -Wno-int-conversion -Wno-unused-result -Wno-unused-result -Wno-vla-parameter -fcode-hoisting -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -Wno-deprecated-declarations -DNDK_SET_VAR -DNDK_UPSTREAM_LIST  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../nginx-rtmp-module -I ../ngx_brotli/deps/brotli/c/include -I ../njs/nginx/../src -I ../njs/nginx/../build -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../ngx_devel_kit-0.3.0/src -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../openssl-1.1.1p/.openssl/include -I ../zlib-cloudflare-1.3.0 -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.3.0/src \
        -o objs/addon/src/ngx_http_srcache_var.o \
        ../srcache-nginx-module-0.32/src/ngx_http_srcache_var.c
../ngx_http_redis-0.3.7/ngx_http_redis_module.c: In function ‘ngx_http_redis_process_header’:
../ngx_http_redis-0.3.7/ngx_http_redis_module.c:530:26: error: ‘ngx_http_upstream_headers_in_t’ has no member named ‘content_encoding’
  530 |             u->headers_in.content_encoding = h;
      |                          ^
make[1]: *** [objs/Makefile:1844: objs/addon/ngx_http_redis-0.3.7/ngx_http_redis_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../srcache-nginx-module-0.32/src/ngx_http_srcache_util.c: In function ‘ngx_http_srcache_response_no_cache’:
../srcache-nginx-module-0.32/src/ngx_http_srcache_util.c:558:39: error: ‘r->headers_out.cache_control’ is a pointer; did you mean to use ‘->’?
  558 |     ccp = r->headers_out.cache_control.elts;
      |                                       ^
      |                                       ->
../srcache-nginx-module-0.32/src/ngx_http_srcache_util.c:564:49: error: ‘r->headers_out.cache_control’ is a pointer; did you mean to use ‘->’?
  564 |     for (i = 0; i < r->headers_out.cache_control.nelts; i++) {
      |                                                 ^
      |                                                 ->
make[1]: *** [objs/Makefile:1893: objs/addon/src/ngx_http_srcache_util.o] Error 1
make[1]: Leaving directory '/svr-setup/nginx-1.23.0'
make: *** [Makefile:10: build] Error 2
```

### PR DESCRIPTION
**Pull request by hnakamur**
This pull request fixes [Nginx 1.23.0 header changes · Issue #96 · openresty/srcache-nginx-module](https://github.com/openresty/srcache-nginx-module/issues/96).
See https://github.com/nginx/nginx/commit/3aef1d693f3cc431563a7e6a6aba6a34e52 for changes in nginx.

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
@hnakamur  you can add v1.23.0 to .travis.yml.

**Comment by hnakamur** [comment]
[Add patch for nginx 1.23.0 by hnakamur · Pull Request #24 · openresty/no-pool-nginx](https://github.com/openresty/no-pool-nginx/pull/24) is needed to be merged for travis nginx 1.23.0 to be successful.

**Comment by zhuizhuhaomeng** [comment]
@hnakamur  no-pool-nginx.patch has been merged.

**Comment by zhuizhuhaomeng** [comment]
@hnakamur would you please retrigger the travis?

**Comment by hnakamur** [comment]
@zhuizhuhaomeng I tried to retrigger the travis, but the "Trigger build" menu in "More options" dropdown at https://app.travis-ci.com/github/openresty/srcache-nginx-module/jobs/574418725 is disabled.
Would you regtrigger the travis instead?

**Comment by zhuizhuhaomeng** [comment]
I can not regiter the travis also. I think you need to add a new commit , eg: add one space in the travis.yml.

**Comment by zhuizhuhaomeng** [comment]
> @zhuizhuhaomeng I tried to retrigger the travis, but the "Trigger build" menu in "More options" dropdown at https://app.travis-ci.com/github/openresty/srcache-nginx-module/jobs/574418725 is disabled. Would you regtrigger the travis instead?

thanks god, I can retrigger the travis after I login travis-ci.com

**Comment by zhuizhuhaomeng** [comment]
Hi @hnakamur thanks your contribution. I have approved this PR.
Because the following three modules are still not compatible with nginx-1.23.0 and the ci can not work properly,  So I will not merge the PR for now.

```
lua-nginx-module
headers-more-nginx-module 
ngx_http_redis
```

**Comment by zhuizhuhaomeng** [comment]
@hnakamur  t/private.t run failed.
function ngx_http_srcache_process_multi_header_lines still think the r->headers_out.headers is an array.
would you please fix it.

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
@hnakamur thank you for your contribution. 
I have merged the PR.
The ci still can not pass due to other issues. We need other PRs to fix the ci.

**Pull request merged**
