### PR TITLE
Sync status lines 307,308 with nginx

### LINKED ISSUE #87: ngx.redirect 307 makes srcache_fetch fail
Hi,

using nginx 1.18 (+ openssl callback patch), http-lua 0.10.19, srcache 0.32, luajit-2.1.20201027 on a debian box,
when i use `ngx.redirect(url)` in `access_by_lua` on a working srcache config, everything's all right.
However if i use `ngx.redirect(url, 307)` i get
```
2020/11/13 14:04:08 [debug] 171078#171078: fetching key "test2.localhost.localdomain" in shared dict "myDomains"
2020/11/13 14:04:08 [debug] 171078#171078: shmtx lock
2020/11/13 14:04:08 [debug] 171078#171078: shmtx unlock
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua redirect to "https://test3.localhost.localdomain:17443/mypath" with code 307
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua resume returned 1
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua thread yielded
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua thread aborting request with status 307
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua request cleanup: forcible=0
2020/11/13 14:04:08 [debug] 171078#171078: *60 http lua finalize threads
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua deleting light thread 00007FAC45F13F00 (ref 2)
2020/11/13 14:04:08 [debug] 171078#171078: *60 lua caching unused lua thread 00007FAC45F13F00 (ref 2)
2020/11/13 14:04:08 [debug] 171078#171078: *60 http finalize request: 307, "/mypath?" a:1, c:1
2020/11/13 14:04:08 [debug] 171078#171078: *60 http special response: 307, "/mypath?"
2020/11/13 14:04:08 [debug] 171078#171078: *60 http script var: "0"
2020/11/13 14:04:08 [debug] 171078#171078: *60 srcache_store decides to store the response
2020/11/13 14:04:08 [debug] 171078#171078: *60 srcache store header HTTP/1.1 307
Content-Type: text/html
Location: https://test3.localhost.localdomain:17443/mypath

2020/11/13 14:04:08 [error] 171078#171078: *60 srcache_fetch: buffer error when serializing the response header: -17 left, client: 127.0.0.1, server: _, request: "GET /mypath HTTP/2.0", host: "test2.localhost.localdomain:17443"
2020/11/13 14:04:08 [debug] 171078#171078: *60 http finalize request: -1, "/mypath?" a:1, c:1
2020/11/13 14:04:08 [debug] 171078#171078: *60 http terminate request count:1
2020/11/13 14:04:08 [debug] 171078#171078: *60 http terminate cleanup count:1 blk:0
2020/11/13 14:04:08 [debug] 171078#171078: *60 http posted request: "/mypath?"
2020/11/13 14:04:08 [debug] 171078#171078: *60 http terminate handler count:1
2020/11/13 14:04:08 [debug] 171078#171078: *60 http request count:1 blk:0
2020/11/13 14:04:08 [debug] 171078#171078: *60 http2 close stream 1, queued 0, processing 1, pushing 0
2020/11/13 14:04:08 [debug] 171078#171078: *60 http2 send RST_STREAM frame sid:1, status:2
2020/11/13 14:04:08 [debug] 171078#171078: *60 http close request
```
and the client dies with
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

For comparison here's the log with a "standard" redirection:
```
2020/11/13 14:11:18 [debug] 173222#173222: fetching key "test2.localhost.localdomain" in shared dict "myDomains"
2020/11/13 14:11:18 [debug] 173222#173222: shmtx lock
2020/11/13 14:11:18 [debug] 173222#173222: shmtx unlock
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua redirect to "https://test3.localhost.localdomain:17443/mypath" with code 307
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua resume returned 1
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua thread yielded
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua thread aborting request with status 307
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua request cleanup: forcible=0
2020/11/13 14:11:18 [debug] 173222#173222: *7 http lua finalize threads
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua deleting light thread 00007F9E5E1BADB0 (ref 2)
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua caching unused lua thread 00007F9E5E1BADB0 (ref 2)
2020/11/13 14:11:18 [debug] 173222#173222: *7 http finalize request: 307, "/mypath?" a:1, c:1
2020/11/13 14:11:18 [debug] 173222#173222: *7 http special response: 307, "/mypath?"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http script var: "0"
2020/11/13 14:11:18 [debug] 173222#173222: *7 srcache_store bypassed because of unmatched status code 307 with srcache_store_statuses
2020/11/13 14:11:18 [debug] 173222#173222: *7 headers more header filter, uri "/mypath"
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua header filter for user lua code, uri "/mypath"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http cleanup add: 000055A7B2533998
2020/11/13 14:11:18 [debug] 173222#173222: *7 code cache lookup (key='header_filter_by_lua_nhli_46c354449c5f02150cba6fbbeb9a2288', ref=-1)
2020/11/13 14:11:18 [debug] 173222#173222: *7 code cache miss (key='header_filter_by_lua_nhli_46c354449c5f02150cba6fbbeb9a2288', ref=-1)
2020/11/13 14:11:18 [debug] 173222#173222: fetching key "test2.localhost.localdomain" in shared dict "upcacheLocks"
2020/11/13 14:11:18 [debug] 173222#173222: shmtx lock
2020/11/13 14:11:18 [debug] 173222#173222: shmtx unlock
2020/11/13 14:11:18 [info] 173222#173222: *7 [lua] upcache.lua:50: response(): response key 'nil', client: 127.0.0.1, server: _, request: "GET /mypath HTTP/2.0", host: "test2.localhost.localdomain:17443"
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua capture header filter, uri "/mypath"
2020/11/13 14:11:18 [debug] 173222#173222: *7 charset: "" > "utf-8"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 header filter
2020/11/13 14:11:18 [debug] 173222#173222: *7 posix_memalign: 000055A7B2535AC0:4096 @16
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: ":status: 307"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "server: nginx"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "date: Fri, 13 Nov 2020 13:11:18 GMT"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "content-type: text/html; charset=utf-8"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "content-length: 164"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "location: https://test3.localhost.localdomain:17443/mypath"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 output header: "strict-transport-security: max-age=63072000; includeSubDomains; preload"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2:1 create HEADERS frame 000055A7B2535BF8: len:166 fin:0
2020/11/13 14:11:18 [debug] 173222#173222: *7 http cleanup add: 000055A7B2535D00
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 frame out: 000055A7B2535BF8 sid:1 bl:1 len:166
2020/11/13 14:11:18 [debug] 173222#173222: *7 SSL buf copy: 9
2020/11/13 14:11:18 [debug] 173222#173222: *7 SSL buf copy: 166
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2:1 HEADERS frame 000055A7B2535BF8 was sent
2020/11/13 14:11:18 [debug] 173222#173222: *7 http2 frame sent: 000055A7B2535BF8 sid:1 bl:1 len:166
2020/11/13 14:11:18 [debug] 173222#173222: *7 http output filter "/mypath?"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http copy filter: "/mypath?"
2020/11/13 14:11:18 [debug] 173222#173222: *7 lua capture body filter, uri "/mypath"
2020/11/13 14:11:18 [debug] 173222#173222: *7 http postpone filter "/mypath?" 000055A7B2535E40
```

### PR DESCRIPTION
**Pull request by kapouer**
This fixes #87

### CODE REVIEW

**Comment by kapouer** [comment]
Any idea if this is going to be accepted ?

**Comment by zhuizhuhaomeng** [comment]
we need to add some test case to cover the changes.

**Comment by kapouer** [comment]
ok i'm adding some

**Comment by kapouer** [comment]
@zhuizhuhaomeng I added 307/308 statuses code in the default store status responses, because it makes so much sense with 301/302 next to them.

**Comment by zhuizhuhaomeng** [comment]
merged

**Pull request closed without merging**
