### PR TITLE
Convert a config file to build a dynamic module

### PR DESCRIPTION
**Pull request by hnakamur**
Please refer to [Converting Static Modules to Dynamic Modules | NGINX](https://www.nginx.com/resources/wiki/extending/converting/#) for dynamic modules.

### CODE REVIEW

**Comment by agentzh** [comment]
@hnakamur Thanks for the patches. I'll look into them soon :)

**Comment by agentzh** [comment]
@hnakamur I'd like to hold this off since this module has severe compatibility issues with NGINX 1.9.11 and the test suite is failing horribly even with static module mode.

**Comment by agentzh** [comment]
@hnakamur I've merged a modified version of your patch to git master. Thanks for your contribution!

**Comment by hnakamur** [comment]
Thanks!

**Pull request closed without merging**
